dirkjanm/BloodHound.py

bloodhound/ad.py
I've added some error handling to prevent the ingestor from exiting after encountering an error with one server. After this commit the ingestor will print a warning and then continue with the loop.
=> Error handling added to querying sessions.

bloodhound/enumeration/acls.py
```
bloodhound-python -u USER -p PASS -dc lab-dc01.lab.justin-p.me -gc lab-dc01.lab.justin-p.me -d lab.justin-p.me -ns 10.11.12.1 -c all
...
INFO: Querying computer: LAB-DC01.lab.justin-p.me
ERROR: Unhandled exception in computer LAB-DC01.lab.justin-p.me processing: 'ms-mcs-admpwd'
INFO: Traceback (most recent call last):
File "/usr/local/lib/python3.7/dist-packages/bloodhound-1.0.0-py3.7.egg/bloodhound/enumeration/computers.py", line 235, in process_computer
results_q.put(('computer', c.get_bloodhound_data(entry, self.collect)))
File "/usr/local/lib/python3.7/dist-packages/bloodhound-1.0.0-py3.7.egg/bloodhound/ad/computer.py", line 151, in get_bloodhound_data
self.addc.objecttype_guid_map)
File "/usr/local/lib/python3.7/dist-packages/bloodhound-1.0.0-py3.7.egg/bloodhound/enumeration/acls. …
```
=> fixes ms-mcs-admpwd check in acls.py when there is no LAPS attributes in the environment.

bloodhound/ad/authentication.py
These two tweaks will help with proxied or slow connections.
1. 60 seconds is just arbitrarily larger and helped in my specific case where proxychains over a slow HTTPS connection was making the results timeout.
2. auto_range allows LDAP3 to pull in more results to Bloodhound.py at one time. This increases the RAM hit, but also decreases timeouts and errors.
I have tested these tweaks in a couple scenarios and they have generally made things go smoother. I don't know if that will be the case for everyone.
=> Increase Timeout and Auto_Range

bloodhound/enumeration/acls.py
Writing rights allow to write msDS-AllowedToActOnBehalfOfOtherIdentity attribute used for resource based constrained delegation.
=> Add additional ACEs for computers

Dockerfile
The docker builds currently fail due to lack of rust and cargo being present inside the container. This PR adds the dependencies to get the container to build again.
=> Update dockerfile to add rust support

bloodhound/__init__.py, bloodhound/enumeration/computers.py, bloodhound/enumeration/domains.py, bloodhound/enumeration/memberships.py, bloodhound/enumeration/outputworker.py
Compression of output files as an toggle
```
python3 bloodhound.py -c All -d legitcorp.net -dc 'DC01.legitcorp.net' -u Administrator -p 'Passw0rd!123' -ns 192.168.58.111 --zip 
INFO: Found AD domain: legitcorp.net
INFO: Connecting to LDAP server: DC01.legitcorp.net
INFO: Found 1 domains
INFO: Found 1 domains in the forest
INFO: Found 5 computers
INFO: Connecting to LDAP server: DC01.legitcorp.net
INFO: Found 130 users
INFO: Found 75 groups
INFO: Found 0 trusts
INFO: Starting computer enumeration with 10 workers
INFO: Querying computer: WIN10-jIGYB.legitcorp.net
INFO: Querying computer: WIN7DEV-PC.legitcorp.net
INFO: Querying computer: legitcorp.net
INFO: Querying computer: DC01.legitcorp.net
INFO: Ignoring host legitcorp.net since its hostname does not match: Supplied hostname …
```
=> Added timestamp prefix and zip compression of output files

bloodhound/ad/domain.py
self.objecttype_guid_map has a hyphen while the comparison did not and this was causing it to not include the msDS-GroupMSAMembership attribute. 
Because of this https://github.com/fox-it/BloodHound.py/blob/master/bloodhound/enumeration/memberships.py#L205 was failing even when it shouldn't.
=> Fix hyphen typo in gMSA reading functionality.

bloodhound/ad/computer.py, bloodhound/enumeration/computers.py
Hi @dirkjanm!
This is a follow-up pull request regarding the issue #85 I opened a few weeks ago. I added some code to enumerate the logged on users through the Remote Registry. There is nothing special about it. I tried to mimic the way it is already implemented in SharpHound.
Just a couple of things:
- The Remote Registry service is not necessarily started but as soon as you try to access the `\pipe\winreg` named pipe, it is triggered. No need to go through the Service Manager to start it manually, which is nice when you don't have admin privileges.
- In SharpHound, registry session enumeration is included in the "LoggedOn" option, so I did the same thing here.
=> Add registry session enumeration

bloodhound/__init__.py, createforestcache.py
Whilst watching a video from John Hammond about BloodHound he stumbled upon this typo in an error message produced by BloodHound.py. The typo is in the following sentence:
> ERROR: Could not figure out the domain to query. Please specify this manualy with -d
Manually here should be written with two Ls, rather than one.
Timestamp where typo can be seen:
> https://youtu.be/yp8fw72oQvY?t=1415
=> Fix typo: manualy -> manually

bloodhound/enumeration/domains.py, bloodhound/enumeration/memberships.py
When the collector tries to resolve the dn of linked GPOs, there is an uncatched error when a GPO does not exist (anymore).
`get_dn_from_cache_or_ldap` returns `None` if the dn can not be found (`ad/domains.py` line 709), and `None["ObjectIdentifier"]` raises a `TypeError` (and not a `KeyError`). 
Example:
```
>>> None["toto"]
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: 'NoneType' object is not subscriptable
```
=> Handle properly missing linked GPO

bloodhound/enumeration/computers.py
I think there is a mistake in session enumeration.
If a computer hosts multiple net sessions, only one distinct user is reported in `computers.json`. This is due to an error in the key used to cache `sAMAccountName -> objectSid` resolutions.
Currently, the key is `samcache` which contains the `sAMAccountName` of the computer, so it is the same for every sessions.
https://github.com/fox-it/BloodHound.py/blob/21d3414ecaec3eb8e8f57553f296bfe0c7cf61be/bloodhound/enumeration/computers.py#L93
The first session user SID is resolved and cached with `samname` key. Every subsequent session will then use the cached SID instead of resolving and caching the SID of their own user.
The key should instead be the `sAMAccountName` of the session user, which is `ses['user']`.
=> Fix session enumeration caching

bloodhound/ad/computer.py, bloodhound/ad/domain.py, bloodhound/ad/dumpntlm.py, bloodhound/ad/utils.py, bloodhound/enumeration/acls.py, bloodhound/enumeration/computers.py, bloodhound/enumeration/objectresolver.py, bloodhound/enumeration/outputworker.py
This PR resolves computers found in sessions, to their corresponding hostname using **\pipe\wrksta** rpc interface (over smb). This was a missing feature from SharpHound.
The PR contains some minor changes and remove unnecessary imports, but the main changes are in `bloodhound/enumeration/computers.py` and `bloodhound/ad/utils.py` files.
The API name that does the main work is `NetrWkstaGetInfo` which was implemented before in Impacket.
```
Using `NetrWkstaGetInfo` API requires Administrator privileges on target computer.
```
Special thanks to @dirkjanm !
**EDIT**:
New methods added, before using wrksta, which they don't need credentials to get hostname:
- Get hostname using ntlm information over **SMB** (445 port)
- Get hostname using ntlm information over **NetBios** (139 port)
- Get …
=> session resolving using 4 new methods

bloodhound/enumeration/acls.py
An ACE that applies only to descendant objects will also be reported as applying to the object where it is located. This is due to the missing INHERIT_ONLY_ACE condition when the AceType is 0. 
**Steps to Reproduce**
* Select a principal and an object where the principal has no privileges on it, such as an OU.
* On the OU, add an ACE for the principal with privileges GENERIC_ALL that applies only to descendant objects.
* Collect the data and import it into BloodHound.
* Query for relationships between the principal and the OU. The principal will be shown as having GenericAll over the OU when in reality it only applies to descendant objects.
=> Fix INHERIT_ONLY_ACE false positive when AceType == 0 

bloodhound/__init__.py
The calls to ADAuthentication in file init.py lines previously were passing None if -d was not specified, leading to a crash when trying to convert None to lowercase. Defaulted to '' as the ADAuthentication function is expecting
=> Default domain arg to '' instead of None

setup.py
Echoes with https://github.com/dirkjanm/BloodHound.py/pull/120
Without `pycryptodome`, we get the following error
```
INFO: Found AD domain: htb.local
INFO: Getting TGT for user
WARNING: Failed to get Kerberos TGT. Falling back to NTLM authentication. Error: [Errno Connection error (htb.local:88)] [Errno -3] Temporary failure in name resolution
INFO: Connecting to LDAP server: forest.htb.local
Traceback (most recent call last):
File "/root/.local/pipx/venvs/bloodhound/lib/python3.11/site-packages/ldap3/utils/ntlm.py", line 500, in ntowf_v2
from Crypto.Hash import MD4  # try with the Crypto library if present
^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Crypto'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File …
```
=> Adding pycryptodome to setup.py

bloodhound/ad/domain.py, bloodhound/ad/utils.py
- Added collection of sMSA.
- Fixed gMSA name when `msDS-GroupMSAMembership` is empty. In that case, it was set to `NAME.CONTOSO.COM`.
- We must rely on the object classes to detect sMSA and gMSA because `msDS-HostServiceAccountBL` and `ms-DS-GroupMSAMembership` may both be empty. SharpHound collects the MSA even if these properties are empty.
- Removed gMSA samaccountname rstrip of `$` to match SharpHound.
- Removed the collection of MSA as computer objects, which will overwrite the user objects if they are imported as computers afterwards.
You can edit this code however you like.
=> Fix MSA collection and parsing

bloodhound/ad/domain.py
Without setting the DNS resolver timeout, queries still timeout after 3 seconds. Updated so the -dns-timeout flag sets both timeout and lifetime.
=> Fix DNS timeout

bloodhound/ad/utils.py
The regular expression needs to be escaped otherwise a syntax warning message 
`bloodhound/ad/utils.py:115: SyntaxWarning: invalid escape sequence '\-'`
is printed when running bloodhound.py
=> invalid escape sequence fix

bloodhound/ad/utils.py
Hi,
I found a bug in the `get_entry_property` function when a `NoneType` entry is passed:
```
INFO: Found AD domain: LAB.local
WARNING: Could not find a global catalog server, assuming the primary DC has this role
If this gives errors, either specify a hostname with -gc or disable gc resolution with --disable-autogc
INFO: Getting TGT for user
INFO: Connecting to LDAP server: DC01.LAB.local
INFO: Found 1 domains
INFO: Found 1 domains in the forest
INFO: Found 2156 computers
INFO: Connecting to GC LDAP server: DC01.LAB.local
WARNING: LDAP Authentication is refused because LDAP signing is enabled. Trying to connect over LDAPS instead...
INFO: Connecting to LDAP server: DC01.LAB.local
Traceback (most recent call last):
File "/tmp/BloodHound.py/./bloodhound.py", line 5, in <module> …
```
=> [bug-fix] Function get_entry_property() is not expecting a None entry, leading to TypeError: 'NoneType' object is not subscriptable

bloodhound/ad/computer.py, bloodhound/enumeration/memberships.py
This (VERY simple) PR fixes an edge case I encountered in our production environment, where user and computer  objects would have an SPN set for delegation in the following format:
```
Service/HOSTNAME\E0FOOBAR:1337
```
This would be parsed incorrectly by `BloodHound.py`, leading to a fatal error with the `\e0` escape (`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 11: invalid continuation byte`)  upstream in `pyasn1`.
Since the SAM should not contain the extraneous information from this SPN anyway, the fix for this is simple, we add another `split` call to remove anything that does not belong to the ASN. In my testing, this fixed the edge case.
=> Fix edge-case in constrained delegation parsing logic

bloodhound/ad/authentication.py
It would be great to allow authentication when the `-hashes` parameter only contains the NT hash such as `:8846f7eaee8fb117ad06bdd830b7586c`.
This PR implements a simple fix that checks whether the LM hash is empty, and in that case, it replaces it with the LM hash of the empty string.
A note on `ldap3`: we can basically use an arbitrary 32-character long string for this hash since it does not use it anyway as long as it has the proper length. From ldap3:
```python3
def ntowf_v2(self):
passparts = self._password.split(':')
if len(passparts) == 2 and len(passparts[0]) == 32 and len(passparts[1]) == 32:    # <-- STILL NEEDS A 32-CHARACTER LONG LM VALUE TO USE THE NT HASH
password_digest = binascii.unhexlify(passparts[1])    # <-- ONLY USES NT HASH ANYWAY
else:
try:
password_digest = …
```
=> Allow authentication when LM hash is empty

bloodhound/enumeration/acls.py
This pull request adds the collection of two ACLs related to Organizational Units: **GenericWrite** and **Manage Group Policy Links**.
The motivation behind the pull request is described in the following article: https://www.synacktiv.com/publications/ounedpy-exploiting-hidden-organizational-units-acl-attack-vectors-in-active-directory
A similar pull request was created for the C# collector SharpHound. An additional pull request was created for the BloodHound GUI, in order to create two new edges associated with the GenericWrite and Manage Group Policy Links OU ACLs.
=> Additional Organizational Units ACLs

bloodhound/ad/computer.py, bloodhound/ad/domain.py, bloodhound/enumeration/acls.py
The name of the LDAP attributes changed from LAPS Legacy to LAPSv2.
This PR adds checks for the new `msLAPS-PasswordExpirationTime` attribute.
References:
- <https://learn.microsoft.com/en-us/windows-server/identity/laps/laps-technical-reference>
=> add lapsv2 support

bloodhound/ad/computer.py, bloodhound/ad/domain.py
With this PR the additional computer attribute *operatingSystemVersion* is collected from LDAP.
Furthermore the computer object in BloodHound gets the three additional attributes *operatingsystemname*, *operatingsystemservicepack* and *operatingsystemversion* that reflect the values of the respective LDAP attributes. The value of the original *operatingsystem* attribute in BloodHound remains unchanged.
This enables detailed reporting on outdated Windows versions, e.g. unsupported Windows 10 builds.
=> add detailed os version collection

bloodhound/ad/utils.py
Fix this error:
```
Traceback (most recent call last):
File "/home/user/.local/bin/bloodhound-ce-python", line 8, in <module>
sys.exit(main())
~~~~^^
File "/home/user/.local/share/pipx/venvs/bloodhound-ce/lib64/python3.13/site-packages/bloodhound/__init__.py", line 347, in main
bloodhound.run(collect=collect,
~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
num_workers=args.workers,
^^^^^^^^^^^^^^^^^^^^^^^^^
...<4 lines>...
exclude_dcs=args.exclude_dcs,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fileNamePrefix=args.outputprefix)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/user/.local/share/pipx/venvs/bloodhound-ce/lib64/python3.13/site-packages/bloodhound/__init__.py", line 81, in run
membership_enum.enumerate_memberships(timestamp=timestamp, fileNamePrefix=fileNamePrefix) …
```
=> Fix map error in ensure_string

bloodhound/enumeration/domains.py, bloodhound/enumeration/memberships.py
Hi,
I'm working on a tool that analyzes GPOs using BloodHound data and SYSVOL. I successfully reconstructed group policy inheritance based on Neo4j data. However, I noticed that the BloodHound collector does not account for disabled GPO links.
This quick fix ensures that disabled GPO links are excluded from being added to the container.
Let me know if you have any questions.
=> Exclude disabled gpLink
